In [5]:
import cv2
import numpy as np

im_g = cv2.imread("smallgray.png",0)
print(im_g)

im_g[0:2,2:4]


[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


array([[104, 121],
       [255, 255]], dtype=uint8)

In [3]:
for i in im_g:  
    print(i)   #prints each row of the image as a 1D array

for i in im_g.T:
    print(i)    #prints each column of the image as a 1D array 

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]
[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [6]:
sna = np.hstack([im_g,im_g]) #stacks the image horizontally (side by side)
print(sna)

sna2 = np.vstack([im_g,im_g]) #stacks the image vertically (one on top of the other)
print(sna2)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [13]:
sla = np.hsplit(sna,2) #splits the horizontally stacked image into 2 equal parts
print(sla)

sla2 = np.vsplit(sna,3) #splits the vertically stacked image into 3 equal parts
print(sla2)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8), array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8), array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]
