In [4]:
import numpy as np
n = np.arange(27) #creates a one dimensional array with values from 0 to 26
print(n)
n = n.reshape(3,9) #reshapes the array into a 3D array with dimensions 3x9
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]


In [6]:
l1 = [[[2,4,5], [5,17,8]], [[4,5,6], [7,8,9]]]

nu = np.array(l1) #converts the list into a numpy array
print(nu)
type(nu) #prints the type of the variable nu, which is a numpy array
type(l1) #prints the type of the variable l1, which is a list

[[[ 2  4  5]
  [ 5 17  8]]

 [[ 4  5  6]
  [ 7  8  9]]]


list